development:
  adapter: postgresql
  database: breakingnews
  host: localhost
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: breakingnews
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: breakingnews
  host: localhost
  pool: 5
  timeout: 5000

cucumber:
  <<: *test